language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  -  python -m pytest tests --cov=redwind --cov-report term-missing
after_success:
  - coveralls
